# Docker para desarrollo
FROM node:14.3.0

COPY . /app
WORKDIR /app
RUN npm install

ENV MONGODB mongodb://host.docker.internal/authentication
ENV RABBIT_URL amqp://host.docker.internal

# Puerto auth service
EXPOSE 3000

CMD ["npm","start"]
